---
  - hosts: all

    sudo: true

    vars:
      document_root: /vagrant/web
      server_name: machine.dev
      server_alias: www.machine.dev

    roles:
      - webserver
      - database

    pre_tasks:
      - name: update apt chage
        apt: update_cache=yes

      - name: install required packages
        apt: name={{ item }} state=present
        with_items:
          - subversion
          - mercurial
          - cpanminus
