---
  - hosts: all

    become: true

    vars:
      document_root: /home/vagrant/public
      server_name: machine.dev
      server_alias: www.machine.dev

    roles:
      - webserver
      - database
      - memcached

    pre_tasks:
      - name: Update the apt cache
        apt: update_cache=yes

      - name: Install required packages
        apt: name={{ item }} state=present
        with_items:
          - subversion
          - mercurial
          - cpanminus
