---
- name: Install PostgresSQL
  apt: name={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Create the default PostgreSQL user 'u:dev & p:123'
  postgresql_user:
    name=dev
    password=123
    login_user=postgres
    role_attr_flags=CREATEDB,SUPERUSER
  sudo_user: postgres
  notify:
    - restart postgresql
