---
- name: "Checkout Apache::ASP from subversion"
  subversion:
    repo=svn://svn.code.sf.net/p/apache-asp/code/trunk
    dest=/home/vagrant/apache-asp
  register: aspcheckout

- name: "Install the Prerequisites for Apache::ASP"
  shell: cpanm {{ item }}
  with_items:
    - MLDBM
    - MLDBM::Sync
  sudo: yes
  when: aspcheckout.changed

- name: "Run perl Makefile.PL"
  shell: perl Makefile.PL chdir=/home/vagrant/apache-asp
  when: aspcheckout.changed

- name: "Make the Apache::ASP module"
  shell: make chdir=/home/vagrant/apache-asp
  when: aspcheckout.changed

- name: "Run the Apache::ASP tests"
  shell: make test chdir=/home/vagrant/apache-asp
  when: aspcheckout.changed

- name: "Install the Apache::ASP module"
  shell: make install chdir=/home/vagrant/apache-asp
  sudo: yes
  when: aspcheckout.changed
  notify:
    - reload apache
