---
- name: install php
  apt: name={{item}} state=present
  with_items:
    - php5-fpm
    - php5-gd
    - php5-cli
    - php5-pgsql
- name: Enable the new development virtual host
  copy:
    src=www.conf
    dest=/etc/php5/fpm/pool.d/www.conf
    mode=0644
  notify:
    - reload php5-fpm
