---
- name: Install php5 with some required modules
  apt: name={{item}} state=present
  with_items:
    - php5-fpm
    - php5-gd
    - php5-cli
    - php5-pgsql
- name: Update the configuration for php5-fpm
  copy:
    src=www.conf
    dest=/etc/php5/fpm/pool.d/www.conf
    mode=0644
  notify:
    - reload php5-fpm
